name: laravel_notify_fcm
description: "Laravel Notify for Firebase Cloud Messaging (FCM) - Send push notifications to your Flutter app from Laravel."
version: 1.0.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/laravel-notify-fcm
issue_tracker: https://github.com/nylo-core/laravel-notify-fcm/issues
funding:
  - https://github.com/sponsors/agordn52
topics:
  - laravel-fcm
  - push-notifications
  - laravel-push-notifications
  - fcm

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_messaging: ^14.7.0
  nylo_support: ^5.75.3
  device_meta: ^1.1.28
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.3+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
