name: laravel_notify_fcm
description: "Laravel Notify for Firebase Cloud Messaging (FCM) - Send push notifications to your Flutter app from Laravel."
version: 3.1.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/laravel-notify-fcm
issue_tracker: https://github.com/nylo-core/laravel-notify-fcm/issues
funding:
  - https://github.com/sponsors/agordn52
topics:
  - laravel-fcm
  - push-notifications
  - laravel-push-notifications
  - fcm

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_meta: ^3.0.2
  dio: ^5.9.2
  flutter:
    sdk: flutter
  nylo_support: ^7.26.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  mockito: ^5.7.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
